# k8s/django-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  SERVICE_NAME: "django-service"
  SERVICE_VERSION: "1.0.0"
  ALLOWED_HOSTS: "django-service,localhost"
  DB_HOST: "postgres"
  REDIS_HOST: "redis"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"